---
# tasks file for qaproj
  - name: install dependencies for yenkins
    package:
      name: "{{ item }}"
      state: present
    with_items: "{{packages}}"

  - name: download yenkins repos
    command: wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
  - name: import jenkins ci keys
    rpm_key:
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
      state: present
  - name: remove trash version of java
    yum: 
      name: "java"
      state: absent  
  - name: install jenkins
    yum:
      name: "jenkins"
      state: present
  - name: start services
    service:
      name: "{{ item }}"
      state: started
    with_items: "{{ services }}"
  - name: allow port 8000
    shell: iptables -I INPUT -p tcp --dport 8080 -m state --state NEW,ESTABLISHED -j ACCEPT
  - name: Wait for port 8080 to become open on the host, don't start checking for 10 seconds
    wait_for:
      port: 8080
      delay: 15