---
# tasks file for docksible
  - name: install packages for docker
    package:
      name: "{{ item }}"
      state: latest
      update_cache: yes
    with_items: "{{ packages }}"
  - name: Add additional repos
    shell: yum-config-manager --enable extras
  
  - name: make sure docker runs on startup
    service: 
      name: "{{ item }}"
      state: started
    with_items: "{{ services }}"

  - name: Ensure packages are installed
    pip:
      name: "{{ packages }}"
    vars:
      packages:
      - boto
      - boto3
      - docker-compose
  - name: clone the dockercompose repo
    git:
      repo: https://github.com/kinnearjay/Docker.git
      dest: ~/webstuff
  - name: clone the website repo
    git: 
      repo: https://github.com/kinnearjay/kinnearjay.github.io.git
      dest: ~/webstuff/kinnyweb
  


      

    